# https://circleci.com/docs/2.0/defining-multiple-jobs/
# Using the new circleci 2.0 beta!

version: 2
jobs:
  build:
    working_directory: ~/beekeeper
    docker:
      - image: alpine:latest
    steps:
      - run: apk add --update curl
      - run:
            name: Trigger Jobs
            command: |
              # a similar function will liekly get built in into the circleci cli
              function trigger_job() {
                job_name=$1
                curl -u ${CIRCLE_API_TOKEN}: \
                  -d build_parameters[CIRCLE_JOB]=${job_name} \
                  -d revision=$CIRCLE_SHA1 \
                  https://circleci.com/api/v1.1/project/github/RoboJackets/beekeeper/tree/$CIRCLE_BRANCH
              }
              trigger_job smoker
              trigger_job langstroth

  # Run our tasks as independent jobs
  smoker:
    docker:
      - image: golang:1.8.3
    working_directory: ~/beekeeper/smoker
    steps:
      # checkout to root of repo
      - checkout:
          path: ~/beekeeper
      # Submodules
      - run: git submodule update --init --recursive
      - run: make
      - run: make multirelease

  langstroth:
    docker:
      - image: java:8
    working_directory: ~/beekeeper/langstroth
    steps:
      - checkout:
          path: ~/beekeeper
      - run: ./gradlew assemble
      # tests
      - run: ./gradlew check
