# https://circleci.com/docs/2.0/workflows/
# Using the new circleci 2.0 beta!
version: 2
jobs:
  smoker:
    docker:
      - image: golang:1.8.3
    working_directory: ~/beekeeper/smoker
    steps:
      # checkout to root of repo
      - checkout:
          path: ~/beekeeper
      # Submodules
      - run: git submodule update --init --recursive
      - run: make
      - run: make multirelease
  langstroth:
    docker:
      - image: java:8
    working_directory: ~/beekeeper/langstroth
    steps:
      - checkout:
          path: ~/beekeeper
      - run: ./gradlew assemble
      # tests
      - run: ./gradlew check

workflows:
  version: 2
  build_and_test:
    jobs:
      - smoker
      - langstroth
